version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "all"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
