name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run setup
      run: bin/setup
    - name: Run the default task
      run: bundle exec rake
    - name: Generate RBS files
      run: |
        bundle exec rbs-inline lib --output=sig/generated
    - name: Type check with Steep
      run: bundle exec steep check
    - name: Confirm the latest RBS file is committed
      run: |
        git diff sig
